### ISSUE TITLE
Time Zones

### ISSUE THREAD

**Issue by davewatson91** [madpilot/hass-amber-electric#11] opened 2021-06-23 21:34 UTC
Sorry to bother again! 

Looks like times in the forecast are mixed - the nem price is local, but the forecast start/end are in UTC. 

Assuming this is actually what's being fed by the API - is this by design?

**Comment by madpilot** [comment] 2021-06-23 21:47
It's by design, though there is a slight nuance: NEM time is always UTC+10, not local time (unless you are in QLD, but that is a coincidence)

The reasoning is computers are better at UTC, and most users don't care about NEM time, so make the times most users are going to consume easier to deal with.

Those interested in NEM time get the "correct" time. It also acts as a useful debug tool for us

**Comment by davewatson91** [comment] 2021-06-23 21:56
Makes sense - I guess the NEM time becomes a pain when daylight savings rolls around too... 

Thanks for the explanation - was only annoying for graphing - will manipulate it to suit. 

Thanks!

**Comment by madpilot** [comment] 2021-06-23 22:06
I just noticed which repo this is to. 

The hass plugin should honour time zones. I'll reopen

**Comment by madpilot** [comment] 2021-06-23 23:14
This is fixed now. It was a server-side issue - no need to update the plugin.

**Comment by madpilot** [comment] 2021-06-23 23:15
![image](https://user-images.githubusercontent.com/19585/123179434-baf57f00-d4cc-11eb-9d6c-364b28a084fc.png)

**Closed** 2021-06-23 23:16 UTC

**Comment by davewatson91** [comment] 2021-06-23 23:18
Looks good on current price - should it be the same for forecasts? (general & feed-in).

**Comment by madpilot** [comment] 2021-06-23 23:23
Yep

**Comment by davewatson91** [comment] 2021-06-23 23:26
Not coming through for me. 

General price looks good, just not the forecasts. 

![image](https://user-images.githubusercontent.com/51277302/123180250-43c0ea80-d4ce-11eb-992a-72f613a2f374.png)

**Comment by madpilot** [comment] 2021-06-23 23:35
That's correct: 2021-06-24T00:00:00+00:00 = 2021-06-24T10:00:00+10:00

**Comment by davewatson91** [comment] 2021-06-23 23:36
Oh damn, I hadn't even noticed that - I was looking at the time and tz separately, not realising that together they're accurate - time for a coffee I suspect. 

Thanks!

**Comment by madpilot** [comment] 2021-06-23 23:39
I'm on number two for the day already.

**Comment by chiefcomm** [comment] 2021-06-23 23:48
Working perfect thanks @madpilot, hmmm coffee

**Comment by chiefcomm** [comment] 2021-06-23 23:51
by the way it's now honouring the TZ perfectly as my PC is set to France TZ and my phone to AU TZ it works no matter what TZ things are set to.  Wonderful.

**Comment by madpilot** [comment] 2021-06-23 23:52
🎉  I've been doing this for twenty years, and I'm still amazed when timezone work properly. Much like audio on Linux.
